language: go
sudo: false
go:
  - 1.19.x
  - 1.20.x
  - 1.21.x
  - 1.22.x
  - master

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - ./.travis.gofmt.sh
  - make guerrillad
  - make test
